version: '3'
services:
  web:
    build: .
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bin/delayed_job restart && rails s -b 0.0.0.0"
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      COLLABORU_DEV_USER: root
      COLLABORU_DEV_PASSWORD: password
    ports:
      - '3000:3000'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.39
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  bundle: